using System;

namespace LeadisTeam.LeadisJourney.Core.Entities
{
    // UserExperience = Code generated by the user
    public class UserExperience : IEntity
    {
        public virtual int Id { get; set; }
        public virtual string RequestId { get; set; }
        public virtual string UserId { get; set; }
        public virtual string Language { get; set; }
        public virtual string Code { get; set; }
    }
}