using System;

namespace LeadisTeam.LeadisJourney.Core.Entities
{
    // UserExperience = Code generated by the user
    public class UserExperience : IEntity
    {
        public virtual int Id { get; set; }
        public virtual Account Creator { get; set; }
        public virtual DateTime CreationDate { get; set; }
        public virtual string Code { get; set; }

        //private String etat;  etat ?
        //private ExperienceResult result;
        //ExperienceResult ? UserExperienceTreatement ?
    }
}